USE dev;
GO
--CREATE SCHEMA p2t_raw
--DROP SCHEMA p2t_raw

--CREATE SCHEMA p2t_dq;

--CREATE SCHEMA p2t_int
CREATE SCHEMA p2t_trn

--SELECT * FROM INFORMATION_SCHEMA.SCHEMATA 
--WHERE SCHEMA_NAME = 'p2t_raw'